name: Tests

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['MOODLE_402_STABLE']
        php: ['8.1']
        database: ['mysqli']
        include:
          - php: '8.2'
            moodle-branch: 'master'
            database: 'mysqli'

    name: ${{ matrix.moodle-branch }}  php ${{ matrix.php }}  ${{ matrix.database }}

    steps:
      - name: checkout plugin
        uses: actions/checkout@v3
        with:
          path: this-plugin

      - name: add plugin
        uses: actions/checkout@v3
        with:
          repository: ewallah/moodle-enrol_coursecompleted.git
          ref: 'main'
          token: ${{ secrets.PAT }}
          path: extras/enrol_enrolcoursecompleted

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: max_input_vars=5000
          coverage: pcov

      - name: composer
        run: |
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8
           sudo systemctl start mysql.service

      - name: install Moodle
        run: moodle-plugin-ci --ansi install -v --db-user=root --db-pass=root --db-host=127.0.0.1 --plugin this-plugin --extra-plugins=extras
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
     
      - name: phplint
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phplint

      - name: phpcpd
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpcpd

      - name: phpmd
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpmd

      - name: phpdoc
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpdoc

      - name: codechecker
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi codechecker

      - name: validate
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi validate

      - name: savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi savepoints

      - name: grunt
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi grunt

      - name: mustache
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi mustache

      - name: phpunit
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpunit --coverage-text

      - name: behat
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat --profile=chrome
